## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

In [75]:
import numpy as np 
import time
import sys 


In [46]:
arr=np.arange(50,100)
arr

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
       84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [25]:
arr=np.ones((3,3))
print("Original array:\n",arr)
arr=np.pad(arr,1)
print("0 on the border and 1 inside in the array:\n",arr)

Original array:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array:
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


## Exercise 3: Convert a list and tuple into arrays

In [54]:
lst=[1,2,3,4,5,6,7,8]
print("List values are :",lst)
tup=tuple(range(1,7))
print("Tuple values are :",tup)
arr1=np.array(lst[::-1])
print("list converted to array is:",arr1)
arr2=np.array(tup[::-1]).reshape(2,3)
print("Tuple converetd to array is:",arr2)

List values are : [1, 2, 3, 4, 5, 6, 7, 8]
Tuple values are : (1, 2, 3, 4, 5, 6)
list converted to array is: [8 7 6 5 4 3 2 1]
Tuple converetd to array is: [[6 5 4]
 [3 2 1]]


## Also try np.asarray for the problem above! 

In [66]:
lst=[1,2,3,4,5,6,7,8]
print("List values are :",lst)
tup=tuple(range(1,7))
print("Tuple values are :",tup)
arr1=np.asarray(lst)
print("Output of list to array using asarray is:",arr1)
arr1=np.asarray(tup[::-1]).reshape(2,3)
print("Output of list to array using asarray is:",arr1)


List values are : [1, 2, 3, 4, 5, 6, 7, 8]
Tuple values are : (1, 2, 3, 4, 5, 6)
Output of list to array using asarray is: [1 2 3 4 5 6 7 8]
Output of list to array using asarray is: [[6 5 4]
 [3 2 1]]


## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

In [98]:
lst_c=[-17.77777778,-11.11111111,7.33888889,1.11111111,37.72777778]
lst_f=[]
for i in range(0,5):
    ##lst_c.append(input("Please enter centigrades to be converted into Fahrenheit degrees:"))
    lst_f.append(float((lst_c[i])/(5/9))+32)
    lst_f[i] ="%.2f" % lst_f[i]
print("Values in centigrades degrees are:",np.asarray(lst_c))
print("Values in Fahnrenheit degrees are:",np.asarray(lst_f))


Values in centigrades are: [-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]
Values in Fahnrenheit are: ['-0.00' '12.00' '45.21' '34.00' '99.91']


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

In [22]:
arr=np.array([2,3,46])


In [25]:
print("Size of the array: ", arr.size)
print("Length of one array element in bytes: ", arr.itemsize)
print("Total bytes consumed by the elements of the array: ", arr.nbytes)

Size of the array:  3
Length of one array element in bytes:  4
Total bytes consumed by the elements of the array:  12


## Exercise 6: Get the unique elements of an array

In [101]:
lst=[10,10,20,20,30,30]
print("List values are :",lst)
arr1=np.array(lst[:])
print("Original array is:",arr1)
for i in range(len(arr1)):
    if len(arr1)>i:#if we don't specify it will throw index out of bound exception ( index 3 is out of bounds for axis 0 with size 3 after deleting last duplicte the arr1 len will educe to 3 nd it will come inside loop and will have this error)
        #print(i,len(arr1))
        #print(np.count_nonzero(arr1==arr1[i]))#since its an numpy array we can use the count_nonzero function
        #print(arr1[i],arr1)
        if np.count_nonzero(arr1==arr1[i]) >= 2:
            arr1=np.delete(arr1,i)#since its a numpy array , normal array functions like pop and remove wont be available
print("Unique elements of the above array:",arr1)

##Second Array
arr2=np.array([1,1,2,3])
arr2=arr2.reshape(2,2)
print("Original array is:\n",arr2)
for i in range(len(arr2)):
    if len(arr2)>i:
        if np.count_nonzero(arr2==arr2[i]) >= 2:
            arr2=np.delete(arr2,i)
print("Unique elements of the above array:",arr2)      
    


List values are : [10, 10, 20, 20, 30, 30]
Original array is: [10 10 20 20 30 30]
Unique elements of the above array: [10 20 30]
Original array is:
 [[1 1]
 [2 3]]
Unique elements of the above array: [1 2 3]


## Exercise 7: Change the dimension of an array


In [106]:
arr=np.arange(1,10)
print("Original array is:\n",arr)
print("Change array shape to (3, 3) -> 3 rows and 3 columns :\n",arr.reshape(3,3))

Original array is:
 [1 2 3 4 5 6 7 8 9]
Change array shape to (3, 3) -> 3 rows and 3 columns :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

In [108]:
arr=np.linspace(2.5,6.5,num=30)
print(arr)

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

In [125]:
arr1=np.arange(10,31,10)
arr2=np.arange(40,61,10)
print("Array1:",arr1)
print("Array2:",arr2)
arr3=np.stack((arr1,arr2),axis = 1)
print("Converted array:\n",arr3)

Array1: [10 20 30]
Array2: [40 50 60]
Convetred array:
 [[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

In [33]:
arr=np.zeros((5,5))
print("Original array:\n",arr)
arr= arr+np.arange(5) # if we give arr = np.arange it will reshape to array of shape and size 5, so we need 5*5 maatrix hence we need to add arr+the range values 
print("Array Shape:",arr.shape)
print("Row values ranging from 0 to 4.\n",arr)


Original array:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array Shape: (5, 5)
Row values ranging from 0 to 4.
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

In [13]:
lst=[]
for i in range(0,100):
    if (i)%3==0 or (i)%5==0:#if a number is divisible by 3 or 5 must retun zero which means it is multiple of 3 and 5 respectively
        lst.append(i)
        aa1=np.array(lst)
print("list of values that are multiples of 3 or 5 below 100 is :\n",aa1)
print("\n Sum of all the multiples of 3 or 5 below 100 is ",aa1.sum())



list of values that are multiples of 3 or 5 below 100 is :
 [ 0  3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50
 51 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]

 Sum of all the multiples of 3 or 5 below 100 is  2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

In [2]:
x = np.arange(4)
y = np.arange(4)
for a, b in np.nditer([x,y]):
    print(a)
    print(b)

0
0
1
1
2
2
3
3


In [22]:
a1=np.arange(4)
print("One dimensional array:",a1)
a2=np.arange(8).reshape(2,4)
print("Two dimensional array:\n",a2)
x = np.arange(8)
y = np.arange(8)
for x,y in np.nditer([a1,a2]):
    print(x,":",y)
    

One dimensional array: [0 1 2 3]
Two dimensional array:
 [[0 1 2 3]
 [4 5 6 7]]
0 : 0
1 : 1
2 : 2
3 : 3
0 : 4
1 : 5
2 : 6
3 : 7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

In [102]:
ar= np.array([[0.42436315,0.48558583,0.32924763],[0.7439979,0.58220701,0.38213418],[0.5097581,0.34528799,0.1563123 ]],dtype='float64')
print("Original array:\n",ar)
for i in range(0,3):
     for j in range (0,3):
        ##print("array index being referenced is",i,j,"and the value is:",ar[i][j])
        if np.any(ar[i][j]>.5):#checking for value within array for values greater than .5
            print("\nArray value greater than .5 is in index ",(i,j),"and the value is ",ar[i][j])
            ar[i][j]=.5
print("\n Replace all elements of the said array with .5 which are greater than .5 \n",ar)
   

Original array:
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]

Array value greater than .5 is in index  (1, 0) and the value is  0.7439979

Array value greater than .5 is in index  (1, 1) and the value is  0.58220701

Array value greater than .5 is in index  (2, 0) and the value is  0.5097581

 Replace all elements of the said array with .5 which are greater than .5 
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

In [119]:
ar=np.array([])
print("Empty Array:",ar)
ar=np.arange(10,70,10).reshape(2,3)
print("After adding two new arrays: \n",ar)

Empty Array: []
After adding two new arrays: 
 [[10 20 30]
 [40 50 60]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

In [206]:
a1=np.array([1,2,3])
a2=np.array([2,3,4])
print("Original array :\n",a1,"\n",a2)
ar=np.array([a1,a2])
print("Sequence of arrays along a new axis:\n",ar)
#np.swapaxes(ar,0,1)
print("Original arrays:\n",np.vstack(a1),"\n \n",np.vstack(a2))
ar=np.concatenate((a1,a2))
print("Sequence of arrays along a new axis:\n",np.vstack(ar))



Original array :
 [1 2 3] 
 [2 3 4]
Sequence of arrays along a new axis:
 [[1 2 3]
 [2 3 4]]
Original arrays:
 [[1]
 [2]
 [3]] 
 
 [[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
 [[1]
 [2]
 [3]
 [2]
 [3]
 [4]]
